// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkt2PS2lGz7W5r90a6u4PHYLPhL7Kl8xc',
    appId: '1:752033387944:web:25c34a22df2e17f154799d',
    messagingSenderId: '752033387944',
    projectId: 'plant-app-9cdae',
    authDomain: 'plant-app-9cdae.firebaseapp.com',
    storageBucket: 'plant-app-9cdae.firebasestorage.app',
    measurementId: 'G-0RTSG04FZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrC1bVPXbc6kJB3q52e7NWkyovWPqDes0',
    appId: '1:752033387944:android:ad287dbb1d6966b954799d',
    messagingSenderId: '752033387944',
    projectId: 'plant-app-9cdae',
    storageBucket: 'plant-app-9cdae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABODQszPr0Fxk4aNHmvqzl6qJvel5zUgE',
    appId: '1:752033387944:ios:6b7de045e960f62854799d',
    messagingSenderId: '752033387944',
    projectId: 'plant-app-9cdae',
    storageBucket: 'plant-app-9cdae.firebasestorage.app',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABODQszPr0Fxk4aNHmvqzl6qJvel5zUgE',
    appId: '1:752033387944:ios:6b7de045e960f62854799d',
    messagingSenderId: '752033387944',
    projectId: 'plant-app-9cdae',
    storageBucket: 'plant-app-9cdae.firebasestorage.app',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkt2PS2lGz7W5r90a6u4PHYLPhL7Kl8xc',
    appId: '1:752033387944:web:aea76678d2b1764654799d',
    messagingSenderId: '752033387944',
    projectId: 'plant-app-9cdae',
    authDomain: 'plant-app-9cdae.firebaseapp.com',
    storageBucket: 'plant-app-9cdae.firebasestorage.app',
    measurementId: 'G-3E16GSFQP5',
  );
}
